### ISSUE TITLE
Add support for multiple blockDeviceMapping

### ISSUE THREAD

**Issue by jaredhocutt** [openshift/cluster-api-provider-aws#231]
The creation of an AWS instance currently only supports a single blockDeviceMapping as indicated here:

https://github.com/openshift/cluster-api-provider-aws/blob/master/pkg/actuators/machine/instances.go#L200

When using other storage providers (i.e. Ceph), they require additional EBS volumes to be attached to the EBS instances. With support for only a single blockDeviceMapping (for the root disk), this makes it impossible to use a MachineSet since you end up having to manually attach EBS volumes after the new machine is up and if it is every replaced, it will no longer have those volumes.

**Comment by netzzer** [comment]
I used MachineSet that had an instance type of M4d.xlarge for deploying rook-ceph pods that included a 75 NVMe SSD (Instance Store).

**Comment by enxebre** [comment]
Covered by https://github.com/openshift/cluster-api-provider-aws/pull/299
