### ISSUE TITLE
Add support to specify the type for spot instances

### ISSUE THREAD

**Issue by rasheedamir** [openshift/cluster-api-provider-aws#338]
In order to have the possibility to stop spot instances it must have be **persistent Spot Instance request**

**Comment by rasheedamir** [comment]
@JoelSpeed ^^

**Comment by JoelSpeed** [comment]
Unfortunately, `stopping` spot instances is incompatible with the design of the Machine API and would not fit with our model.

See: https://github.com/openshift/enhancements/blob/master/enhancements/machine-api/spot-instances.md#persistent-requests

Perhaps you could explain your use case and we may be able to suggest an alternative workaround?
